version: 0.0

environment_variables:
    plaintext:
        "INPUT_FILE": "saml.yaml"
        "S3_BUCKET": "ddbucketofun"

containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - npm install
                    - aws cloudformation package --template-file $INPUT_FILE --s3-bucket $S3_BUCKET --output-template-file post-saml.yaml
        artifacts:
            files:
                - post-saml.yaml
                - beta.json
